site_name: Angry Data Scanner
site_description: Aggregated documentation for the Angry Data Scanner platform.
site_url: https://angryscan.org/
repo_url: https://github.com/angryscan/angrydata-app
repo_name: View on GitHub
use_directory_urls: true
copyright: © 2025, by admin@angryscan.org
hooks:
- hooks.py
theme:
  name: material
  language: en
  palette:
  - scheme: slate
    primary: custom
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
- admonition
- codehilite
- footnotes
- md_in_html
- meta
- pymdownx.details
- pymdownx.superfences
plugins:
- awesome-pages
- i18n:
    docs_structure: folder
    languages:
    - locale: en
      name: English
      default: true
    - locale: ru
      name: Русский
    - locale: es
      name: Español
    - locale: de
      name: Deutsch
    - locale: fr
      name: Français
    reconfigure_material: true
    fallback_to_default: true
- minify:
    minify_html: true
extra_javascript: []
extra_css: []
extra:
  generator: false
  alternate:
  - name: English
    lang: en
    link: /
  - name: Русский
    lang: ru
    link: /ru/
  - name: Español
    lang: es
    link: /es/
  - name: Deutsch
    lang: de
    link: /de/
  - name: Français
    lang: fr
    link: /fr/
